export const FETCH_EVENT_PULSE_REQUEST = 'FETCH_EVENT_PULSE_REQUEST'
export const FETCH_EVENT_PULSE_SUCCESS = 'FETCH_EVENT_PULSE_SUCCESS'
export const FETCH_EVENT_PULSE_FAILURE = 'FETCH_EVENT_PULSE_FAILURE'
