export const FETCH_MEDIA_SIGNAL_REQUEST = 'FETCH_MEDIA_SIGNAL_REQUEST'
export const FETCH_MEDIA_SIGNAL_SUCCESS = 'FETCH_MEDIA_SIGNAL_SUCCESS'
export const FETCH_MEDIA_SIGNAL_FAILURE = 'FETCH_MEDIA_SIGNAL_FAILURE'
