export const FETCH_SENTIMENT_SIGNAL_REQUEST = 'FETCH_SENTIMENT_SIGNAL_REQUEST'
export const FETCH_SENTIMENT_SIGNAL_SUCCESS = 'FETCH_SENTIMENT_SIGNAL_SUCCESS'
export const FETCH_SENTIMENT_SIGNAL_FAILURE = 'FETCH_SENTIMENT_SIGNAL_FAILURE'
